name: Build and Deploy
on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  id-token: write
  contents: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  build:
    name: Build Docker Image And Extract Files For Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git user to current actor
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create beta directory
        run: mkdir -p beta
      - name: Clone repo_beta into beta
        run: git clone https://github.com/kovacs-zsolt-nxtroy/repo_beta beta
      - name: Clone repo_beta into beta
        run: ls -la
      - name: Copy data/ to beta/alfa_data
        run: |
          mkdir -p beta/alfa_data
          cp -r data/* beta/alfa_data/

      - name: Commit and push to repo_beta
        working-directory: beta
        run: |
          git add alfa_data
          git commit -m "$(date +'%Y-%m-%d')_beta frissites" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.REPO_BETA_TOKEN }}@github.com/kovacs-zsolt-nxtroy/repo_beta HEAD:main