name: Build and Deploy
on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  id-token: write
  contents: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  build:
    name: Build Docker Image And Extract Files For Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git user to current actor
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create beta directory
        run: mkdir -p beta
      - name: Clone repo_beta into beta
        run: git clone https://github.com/kovacs-zsolt-nxtroy/repo_beta beta
      - name: Clone repo_beta into beta
        run: ls -la