name: Build and Deploy
on:
  push:
    branches:
      - '**'
permissions:
  actions: read
  id-token: write
  contents: read
  checks: write
  issues: read
  pull-requests: write

jobs:
  build:
    name: Build Docker Image And Extract Files For Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Git user to current actor
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create alfa directory
        run: mkdir -p alfa
      - name: Clone repo_alfa into alfa
        run: git clone https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/kovacs-zsolt-nxtroy/repo_alfa alfa
      - name: Copy data/ to alfa/beta_data
        run: |
          mkdir -p alfa/beta_data
          cp -r data/* alfa/beta_data/

      - name: Commit and push to repo_beta
        working-directory: alfa
        run: |
          ORIGINAL_MESSAGE=$(git -C ../ log -1 --pretty=%B | head -n 1)
          COMMIT_TIME=$(date +'%Y-%m-%d_%H:%M')
          REPO_NAME=$(basename -s .git "$(git config --get remote.origin.url)")
          git add beta_data
          git commit -m "${COMMIT_TIME} ${REPO_NAME} update: ${ORIGINAL_MESSAGE}" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.REPO_TOKEN }}@github.com/kovacs-zsolt-nxtroy/repo_alfa HEAD:main